spring.application.name=School-Education

spring.datasource.url = jdbc:postgresql://localhost:5432/schooleducation
spring.datasource.username = postgres
spring.datasource.password= Thoris10

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
